from __future__ import annotations

from collections import defaultdict

from logicchart.model import Flow, FlowNode, NodeKind, ProjectModel


def render_markdown(model: ProjectModel) -> str:
    entrypoints = [flow for flow in model.flows if flow.is_entrypoint]
    lines = [
        "# LogicChart Decision Flows",
        "",
        "> Generated from source code. Do not edit this file manually.",
        "",
        f"- **Generated:** `{model.generated_at}`",
        f"- **Source root:** `{model.root}`",
        f"- **Flows:** {len(model.flows)}",
        f"- **Entry points:** {len(entrypoints)}",
        f"- **Potential gaps:** {len(model.findings)}",
        "",
        "## Project Map",
        "",
    ]
    lines.extend(_project_map(model, entrypoints))
    lines.extend(["", "## Findings", ""])
    if model.findings:
        for finding in model.findings:
            source = _source_reference(finding.location.path, finding.location.start_line)
            lines.append(
                f"- **{finding.severity.value.upper()} · {finding.kind}** "
                f"{finding.message} ({source})"
            )
    else:
        lines.append("No potential gaps were detected.")

    lines.extend(["", "## Entry Point Flows", ""])
    for flow in entrypoints:
        lines.extend(_flow_section(flow, model))

    subflows = [
        flow for flow in model.flows if not flow.is_entrypoint and not flow.metadata.get("test")
    ]
    if subflows:
        lines.extend(["", "## Referenced Subflows", ""])
        for flow in subflows:
            if flow.called_by:
                lines.extend(_flow_section(flow, model))

    return "\n".join(lines).rstrip() + "\n"


def _project_map(model: ProjectModel, entrypoints: list[Flow]) -> list[str]:
    if not entrypoints:
        return ["No entry points were detected."]
    by_id = {flow.id: flow for flow in model.flows}
    lines = ["```mermaid", "flowchart LR"]
    rendered_nodes: set[str] = set()
    for flow in entrypoints:
        lines.append(f'  {_mermaid_id(flow.id)}["{_escape(flow.name)}"]')
        rendered_nodes.add(flow.id)
    rendered: set[tuple[str, str]] = set()
    for flow in entrypoints:
        for target_id in flow.calls:
            target = by_id.get(target_id)
            if target is None:
                continue
            pair = (flow.id, target.id)
            if pair in rendered:
                continue
            rendered.add(pair)
            if target.id not in rendered_nodes:
                lines.append(f'  {_mermaid_id(target.id)}["{_escape(target.name)}"]')
                rendered_nodes.add(target.id)
            lines.append(f"  {_mermaid_id(flow.id)} --> {_mermaid_id(target.id)}")
    lines.append("```")
    return lines


def _flow_section(flow: Flow, model: ProjectModel) -> list[str]:
    findings_by_node: dict[str, list[str]] = defaultdict(list)
    for finding in model.findings:
        if finding.flow_id == flow.id and finding.node_id:
            findings_by_node[finding.node_id].append(finding.message)

    source = _source_reference(flow.location.path, flow.location.start_line)
    lines = [
        f"### {flow.name}",
        "",
        f"`{flow.entry_kind}` · `{flow.language}` · `{flow.framework}` · {source}",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    for node in flow.nodes:
        lines.append(f"  {_render_node(node)}")
    for edge in flow.edges:
        label = f'|"{_escape(edge.label)}"|' if edge.label else ""
        lines.append(f"  {_mermaid_id(edge.source)} -->{label} {_mermaid_id(edge.target)}")
    lines.append("```")
    if findings_by_node:
        lines.extend(["", "**Review points:**"])
        for node_id, messages in findings_by_node.items():
            node = next(item for item in flow.nodes if item.id == node_id)
            for message in messages:
                lines.append(f"- `{node.label}`: {message}")
    lines.append("")
    return lines


def _render_node(node: FlowNode) -> str:
    node_id = _mermaid_id(node.id)
    label = _escape(node.label)
    if node.kind is NodeKind.DECISION:
        return f'{node_id}{{"{label}"}}'
    if node.kind is NodeKind.CALL:
        return f'{node_id}[["{label}"]]'
    if node.kind is NodeKind.ERROR:
        return f'{node_id}{{{{"{label}"}}}}'
    if node.kind in {NodeKind.ENTRY, NodeKind.TERMINAL}:
        return f'{node_id}(["{label}"])'
    return f'{node_id}["{label}"]'


def _mermaid_id(value: str) -> str:
    return "m" + "".join(character if character.isalnum() else "_" for character in value)


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', "&quot;").replace("\n", " ")


def _source_reference(path: str, line: int) -> str:
    return f"[`{path}:{line}`](../{path}#L{line})"
